#!/bin/sh

# - - - - - - - -
# Exports
# - - - - - - - -

export VISUAL=vim
export EDITOR=vim

# - - - - - - - -
# Cursor
# - - - - - - - -

xsetroot -cursor_name left_ptr
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" -0.4
xinput --set-prop pointer:"Razer Razer DeathAdder Elite" \
                          "libinput Accel Speed" -0.72

# - - - - - - - -
# Autostart
# - - - - - - - -

sxhkd &                           # Keybord shortcuts
fcitx &                           # Keyboard IME
dunst &                           # Notification mgr
flameshot &                       # Screenshot mgr
start-pulseaudio-x11              # Audio
$HOME/.config/polybar/launch.sh & # Bar

# - - - - - - - -
# Monitors
# - - - - - - - -

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# - - - - - - - -
# Configs
# - - - - - - - -

bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          28
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#3e3e3e"
bspc config normal_border_color  "#222222"

# - - - - - - - -
# Rules
# - - - - - - - -

bspc rule -a discord              desktop='^2' border=off follow=off
bspc rule -a TelegramDesktop      desktop='^3' border=off
bspc rule -a firefox              desktop='^4' border=off follow=on
bspc rule -a OpenBoard            border=off state=tiled follow=on
bspc rule -a firefox:Toolkit      state=floating
bspc rule -a firefox:Places       state=floating
bspc rule -a Nemo                 state=floating rectangle=1200x700+360+190
bspc rule -a Pavucontrol          state=floating rectangle=570x400+675+340
bspc rule -a Blueberry.py         state=floating border=off
bspc rule -a Lxappearance         state=floating
bspc rule -a Gpicview             state=floating
bspc rule -a Gvim                 state=floating
bspc rule -a Vimb                 state=floating border=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a vlc                  state=floating 
bspc rule -a qBittorrent          state=floating
bspc rule -a dolphin-emu          state=floating
bspc rule -a Fcitx-config-gtk3    state=floating
bspc rule -a kitty                state=floating
bspc rule -a kitty:float          state=floating
bspc rule -a kitty:tiled          state=tiled
bspc rule -a Zathura              state=tiled
bspc rule -a ru-turikhay-tlauncher-bootstrap-Bootstrap  state=floating

# - - - - - - - - - - - - -
# Compositor and Wallpaper
# - - - - - - - - - - - - -

feh --bg-fill $HOME/Pictures/Wallpapers/full-moon-night.png

$HOME/.config/scripts/feh-blur -s
$HOME/.config/scripts/feh-blur -d -b 4

picom --no-dock-shadow &

# - - - - - - - -
# Lockscreen
# - - - - - - - -

$HOME/.config/scripts/betterlockscreen -w dim
source ~/.fehbg 

