#!/bin/sh
# Script made for the Bluetooth polybar module, cloned from
# https://github.com/msaitz/polybar-bluetooth
# Modified by Álvaro Schachner, to unify the scrpt in one file

display() {
  if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
  then
    echo "%{F#66ffffff}"
  else
    if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
    then 
      echo ""
    fi
    echo "%{F#2193ff}"
  fi
}

switch() {
  if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
  then
    bluetoothctl power on
  else
    bluetoothctl power off
  fi
}

main() {
  if [ $1 = "--display" ];
  then
    display "$@"
  elif [ $1 = "--switch" ];
  then
    switch "$@"
  fi
}

main "$@"

