#!/bin/sh
display() {
  if ping -q -c 1 -W 1 8.8.8.8 >/dev/null 2>&1;
  then
    echo "  "
  fi
  echo " %{F#80ffffff} "
}

switch() {
  if ping -q -c 1 -W 1 8.8.8.8 >/dev/null;
  then
    nmcli networking off
  else
    nmcli networking on
  fi
}

main() {
  if [ $1 = "--display" ];
  then
    display "$@"
  elif [ $1 = "--switch" ];
  then
    switch "$@"
  fi
}

main "$@"
